server:
  port: 8080
spring:
  application:
    name: Holiday Request
  datasource:
    name: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    # hikari连接池配置
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DataPoolHikari
      max-lifetime: 180000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update

okta:
  oauth2:
    client-id:
    issuer: https://dev-757221.okta.com/oauth2/default